### ISSUE TITLE
Request: support configurable url paths (like FontAwesome does it)

### ISSUE THREAD

**Issue by lonix1** [KyleAMathews/typefaces#79]
The `index.css` references fonts in the `./files/` directory, so the declaration has this for example:

    url('./files/open-sans-latin-400.woff2') format('woff2')

But what if our assets aren't structured that way, so the fonts aren't in `./files/`?

It is easy to solve this using the [same approach as Font Awesome](https://fontawesome.com/how-to-use/on-the-web/using-with/sass#compile). For each package add two new files: `_variables.scss` and `index.scss`.

`_variables.scss` has one line:
````scss
$font-path: "./files";        // this is the default, but we can override it
````

`index.scss` file:
````scss
@import "_variables.scss";
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src:
    local('Open Sans'),
    url('#{$font-path}/open-sans-latin-400.woff2') format('woff2')
    // etc...
}
````

So our build scripts can redefine `$font-path` and include all the `index.scss` files. Very easy.

And this would be alongside the existing `index.css` so it wouldn't break anything for existing users.

**SUMMARY**
Just add two new files with the stuff above. Nothing else changes.
